from PyQt5.QtWidgets import *
class PageInput2(QWidget):
    def __init__(self, parent=None):
        super().__init__()


        self.lDownhole1 = QLabel(self)
        self.lDownhole1.move(20, 20)
        self.lDownhole1.resize(180, 20)
        self.lDownhole1.setText('Забой скважины(проект) MD')
        self.inDownhole11 = QLineEdit(self)
        self.inDownhole11.move(200, 10)
        self.inDownhole11.resize(50, 40)
        self.inDownhole11.setPlaceholderText('MD')
        self.lDownhole112 = QLabel(self)
        self.lDownhole112.move(250, 20)
        self.lDownhole112.setText('м  TVD')

        self.inDownhole12 = QLineEdit(self)
        self.inDownhole12.move(300, 10)
        self.inDownhole12.resize(50, 40)
        self.inDownhole12.setPlaceholderText('TVD')
        self.lDownhole122 = QLabel(self)
        self.lDownhole122.move(350, 20)
        self.lDownhole122.setText('м')

        self.lDownhole21 = QLabel(self)
        self.lDownhole21.move(20, 60)
        self.lDownhole21.resize(180, 20)
        self.lDownhole21.setText('Забой скважины(факт) MD')
        self.inDownhole21 = QLineEdit(self)
        self.inDownhole21.move(200, 50)
        self.inDownhole21.resize(50, 40)
        self.inDownhole21.setPlaceholderText('MD')
        self.lDownhole212 = QLabel(self)
        self.lDownhole212.move(250, 60)
        self.lDownhole212.setText('м  TVD')

        self.inDownhole22 = QLineEdit(self)
        self.inDownhole22.move(300, 50)
        self.inDownhole22.resize(50, 40)
        self.inDownhole22.setPlaceholderText('TVD')
        self.lDownhole222 = QLabel(self)
        self.lDownhole222.move(350, 50)
        self.lDownhole222.setText('м')

        self.lDiamOpenBarrel = QLabel(self)
        self.lDiamOpenBarrel.move(20, 100)
        self.lDiamOpenBarrel.resize(180, 20)
        self.lDiamOpenBarrel.setText('Диаметр открытого ствола')
        self.inDiamOpenBarrel = QLineEdit(self)
        self.inDiamOpenBarrel.move(200, 90)
        self.inDiamOpenBarrel.resize(50, 40)
        self.lDiamOpenBarrel2 = QLabel(self)
        self.lDiamOpenBarrel2.move(250, 100)
        self.lDiamOpenBarrel2.setText('мм')

        self.lOffsetFromVert = QLabel(self)
        self.lOffsetFromVert.move(20, 140)
        self.lOffsetFromVert.resize(180, 20)
        self.lOffsetFromVert.setText('Смещение от вертикали')
        self.inOffsetFromVert = QLineEdit(self)
        self.inOffsetFromVert.move(200, 130)
        self.inOffsetFromVert.resize(50, 40)
        self.lOffsetFromVert2 = QLabel(self)
        self.lOffsetFromVert2.move(250, 140)
        self.lOffsetFromVert2.setText('м')

        self.lLenBarrel = QLabel(self)
        self.lLenBarrel.move(20, 180)
        self.lLenBarrel.resize(180, 20)
        self.lLenBarrel.setText('Длина необсаженного ствола')
        self.inLenBarrel = QLineEdit(self)
        self.inLenBarrel.move(200, 170)
        self.inLenBarrel.resize(50, 40)
        self.lLenBarrel2 = QLabel(self)
        self.lLenBarrel2.move(250, 180)
        self.lLenBarrel2.setText('м')

        self.lCorner = QLabel(self)
        self.lCorner.move(20, 220)
        self.lCorner.resize(180, 20)
        self.lCorner.setText('Максимальный зенитный угол')
        self.inCorner = QLineEdit(self)
        self.inCorner.move(200, 210)
        self.inCorner.resize(50, 40)

        self.lInterval = QLabel(self)
        self.lInterval.move(250, 220)
        self.lInterval.setText('º в интервале')
        self.inInterval = QLineEdit(self)
        self.inInterval.move(335, 210)
        self.inInterval.resize(50, 40)
        self.lInterval2 = QLabel(self)
        self.lInterval2.move(385, 220)
        self.lInterval2.setText('м')

        self.lTypeWell = QLabel(self)
        self.lTypeWell.move(400, 20)
        self.lTypeWell.setText('Тип скважины')
        self.inTypeWell = QComboBox(self)
        self.inTypeWell.addItem('Горизонтальная')
        self.inTypeWell.addItem('ЗБС')
        self.inTypeWell.addItem('Наклонно-направленная')
        self.inTypeWell.addItem('Вертикальная')
        self.inTypeWell.addItem('Многоствольная')
        self.inTypeWell.move(550, 10)
        self.inTypeWell.resize(130, 40)

        self.lReservoirPres = QLabel(self)
        self.lReservoirPres.move(400, 60)
        self.lReservoirPres.resize(180, 20)
        self.lReservoirPres.setText('Пластовое давление')
        self.inReservoirPres = QLineEdit(self)
        self.inReservoirPres.move(550, 50)
        self.inReservoirPres.resize(70, 40)
        self.lReservoirPres2 = QLabel(self)
        self.lReservoirPres2.move(620, 60)
        self.lReservoirPres2.resize(100, 40)
        self.lReservoirPres2.setText('МПа')

        self.lWellHeadPres = QLabel(self)
        self.lWellHeadPres.move(400, 100)
        self.lWellHeadPres.resize(180, 20)
        self.lWellHeadPres.setText('Устьевое давление')
        self.inWellHeadPres = QLineEdit(self)
        self.inWellHeadPres.move(550, 90)
        self.inWellHeadPres.resize(70, 40)
        self.lWellHeadPres2 = QLabel(self)
        self.lWellHeadPres2.move(620, 100)
        self.lWellHeadPres2.setText('МПа')

        self.lDesInterShank = QLabel(self)
        self.lDesInterShank.move(400, 140)
        self.lDesInterShank.resize(180, 20)
        self.lDesInterShank.setText('Интервал спуска хвостовика')
        self.inDesInterShank = QLineEdit(self)
        self.inDesInterShank.move(550, 130)
        self.inDesInterShank.resize(70, 40)
        self.lDesInterShank2 = QLabel(self)
        self.lDesInterShank2.move(620, 140)
        self.lDesInterShank2.setText('мм')

        self.lEx = QLabel(self)
        self.lEx.move(700, 20)
        self.lEx.resize(180, 20)
        self.lEx.setText('Эксплуатационная колонна')

        self.lOuterDiam = QLabel(self)
        self.lOuterDiam.move(700, 60)
        self.lOuterDiam.resize(180, 20)
        self.lOuterDiam.setText('Диаметр наружный')
        self.inOuterDiam = QLineEdit(self)
        self.inOuterDiam.move(840, 50)
        self.inOuterDiam.resize(50, 40)
        self.lOuterDiam2 = QLabel(self)
        self.lOuterDiam2.move(890, 60)
        self.lOuterDiam2.setText('мм')
        self.inOuterDiam.setText('178')

        self.lInnerDiam = QLabel(self)
        self.lInnerDiam.move(700, 100)
        self.lInnerDiam.resize(180, 20)
        self.lInnerDiam.setText('Диаметр внутренний')
        self.inInnerDiam = QLineEdit(self)
        self.inInnerDiam.move(840, 90)
        self.inInnerDiam.resize(50, 40)
        self.lInnerDiam2 = QLabel(self)
        self.lInnerDiam2.move(890, 100)
        self.lInnerDiam2.setText('мм')
        self.inInnerDiam.setText('114')

        self.lDescentDepth = QLabel(self)
        self.lDescentDepth.move(700, 140)
        self.lDescentDepth.resize(180, 20)
        self.lDescentDepth.setText('Глубина спуска')
        self.inDescentDepth = QLineEdit(self)
        self.inDescentDepth.move(840, 130)
        self.inDescentDepth.resize(50, 40)
        self.lDescentDepth2 = QLabel(self)
        self.lDescentDepth2.move(890, 140)
        self.lDescentDepth2.setText('м')

        self.lDepthCCODE = QLabel(self)
        self.lDepthCCODE.move(700, 180)
        self.lDepthCCODE.resize(180, 20)
        self.lDepthCCODE.setText('Глубина ЦКОД')
        self.inDepthCCODE = QLineEdit(self)
        self.inDepthCCODE.move(840, 170)
        self.inDepthCCODE.resize(50, 40)
        self.lDepthCCODE2 = QLabel(self)
        self.lDepthCCODE2.move(890, 180)
        self.lDepthCCODE2.setText('м')

        self.lNumberStages = QLabel(self)
        self.lNumberStages.move(400, 180)
        self.lNumberStages.resize(180, 20)
        self.lNumberStages.setText('Кол-во стадий ГРП')
        self.inNumberStages = QLineEdit(self)
        self.inNumberStages.move(550, 170)
        self.inNumberStages.resize(70, 40)
        self.inNumberStages.setText("1")

        self.lcompon = QLabel(self)
        self.lcompon.move(700, 220)
        self.lcompon.resize(180, 20)
        self.lcompon.setText('Тип компоновки')
        self.compon_combo = QComboBox(self)
        self.compon_combo.addItem('Тип №1')
        self.compon_combo.addItem('Тип №2')
        self.compon_combo.addItem('Тип №3')
        self.compon_combo.addItem('Тип №4')
        self.compon_combo.move(840, 210)
        self.compon_combo.resize(130, 40)

        self.butLeft2 = QPushButton('Назад', self)
        self.butLeft2.move(20, 280)

        self.butNext2 = QPushButton('Составить схему', self)
        self.butNext2.move(865, 280)

        self.SetNormalSize()

    def cleanPage(self):
        self.inDownhole11.setText("")
        self.inDownhole12.setText("")
        self.inDownhole21.setText("")
        self.inDownhole22.setText("")
        self.inNumberStages.setText("")


    def SetNormalSize(self):
        for i in self.children():
            try:
                i.x0 = i.x()
                i.y0 = i.y()
                i.width0 = i.width()
                i.height0 = i.height()
            except:
                print("Normal size missed " + i)
    def DynamicSize(self, koefW, koefH):
        for i in self.children():
            try:
                i.resize(int(i.width0 * koefW), int(i.height0 * koefH))
                i.move(int(i.x0 * koefW), int(i.y0 * koefH))

            except:
                print("Dynamic size missed " + i)
